// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzuFjacexx5CEJRT8tQhCgT4mYzKkAoJg',
    appId: '1:461063430823:web:e95f897f1c4222865a7182',
    messagingSenderId: '461063430823',
    projectId: 'frutella-190f6',
    authDomain: 'frutella-190f6.firebaseapp.com',
    storageBucket: 'frutella-190f6.firebasestorage.app',
    measurementId: 'G-5Q148P73KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgg3Tj8INSrkOLGWa2_4nzNijkMnjOaac',
    appId: '1:461063430823:android:9befbcb54bc2761e5a7182',
    messagingSenderId: '461063430823',
    projectId: 'frutella-190f6',
    storageBucket: 'frutella-190f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDonYJp3GXh1Dbpp5ws8_XBH02vkZuaOXU',
    appId: '1:461063430823:ios:9c087c91bc6c401e5a7182',
    messagingSenderId: '461063430823',
    projectId: 'frutella-190f6',
    storageBucket: 'frutella-190f6.firebasestorage.app',
    iosBundleId: 'com.example.fruit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDonYJp3GXh1Dbpp5ws8_XBH02vkZuaOXU',
    appId: '1:461063430823:ios:9c087c91bc6c401e5a7182',
    messagingSenderId: '461063430823',
    projectId: 'frutella-190f6',
    storageBucket: 'frutella-190f6.firebasestorage.app',
    iosBundleId: 'com.example.fruit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzuFjacexx5CEJRT8tQhCgT4mYzKkAoJg',
    appId: '1:461063430823:web:94794d32b9ca4a9b5a7182',
    messagingSenderId: '461063430823',
    projectId: 'frutella-190f6',
    authDomain: 'frutella-190f6.firebaseapp.com',
    storageBucket: 'frutella-190f6.firebasestorage.app',
    measurementId: 'G-BSB6W99BGW',
  );
}
